# SPDX-License-Identifier: CeCILL-2.1 OR AGPL-3.0-or-later
"""The canonical ``DatasetSpec`` IR and its vocabulary."""

from .dataset_spec import (
    SCHEMA_VERSION,
    AggregateSpec,
    ColumnRole,
    DatasetSpec,
    FoldsSpec,
    JoinSpec,
    LoadingParams,
    NaConfig,
    PartitionsSpec,
    SampleIndex,
    SourceSpec,
    ValidationSpec,
    VariationSpec,
)
from .enums import (
    AggregateMethod,
    Cardinality,
    CategoricalMode,
    Coverage,
    FoldFormat,
    HeaderUnit,
    MergeMode,
    Modality,
    NaPolicy,
    Partition,
    PartitionBy,
    Role,
    SampleIndexBy,
    SignalType,
    SourceKind,
    SpecError,
    TaskType,
)
from .selectors import (
    AutoSelector,
    DtypeSelector,
    NameRangeSelector,
    NameSelector,
    PositionalSelector,
    RegexSelector,
    RestSelector,
    Selector,
    SliceSelector,
    parse_selector,
)
from .validate import validate_dict, validate_spec

__all__ = [
    "SCHEMA_VERSION",
    "DatasetSpec",
    "SourceSpec",
    "ColumnRole",
    "JoinSpec",
    "PartitionsSpec",
    "FoldsSpec",
    "AggregateSpec",
    "SampleIndex",
    "LoadingParams",
    "NaConfig",
    "ValidationSpec",
    "VariationSpec",
    # enums
    "Role",
    "SourceKind",
    "Modality",
    "Partition",
    "TaskType",
    "SampleIndexBy",
    "MergeMode",
    "Cardinality",
    "Coverage",
    "HeaderUnit",
    "SignalType",
    "NaPolicy",
    "CategoricalMode",
    "PartitionBy",
    "FoldFormat",
    "AggregateMethod",
    "SpecError",
    # selectors
    "Selector",
    "parse_selector",
    "PositionalSelector",
    "SliceSelector",
    "NameSelector",
    "NameRangeSelector",
    "RegexSelector",
    "DtypeSelector",
    "RestSelector",
    "AutoSelector",
    # validation
    "validate_spec",
    "validate_dict",
]
