/*
 * nirs4all-io C ABI header (symbol prefix n4io_).
 *
 * Generated by cbindgen; do not edit by hand. Refresh with:
 *   cargo build -p nirs4all-io-capi
 *
 * The committed copy under crates/nirs4all-io-capi/include/nirs4all_io.h
 * mirrors the latest build so downstream packagers can pin the header
 * without running cargo.
 *
 * SPDX-License-Identifier: CeCILL-2.1 OR AGPL-3.0-or-later
 */

#ifndef NIRS4ALL_IO_H
#define NIRS4ALL_IO_H

/* Generated with cbindgen:0.27.0 */

/* This file is auto-generated by cbindgen. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Return the ABI version as a freshly allocated C string.
//
// The caller owns the returned pointer and MUST release it with
// [`n4io_string_free`]; never free it with the host allocator.
//
// # Safety
// The returned pointer is non-null and points to a NUL-terminated UTF-8
// string allocated by this library.
char *n4io_abi_version(void);

// Free a string previously returned by this library.
//
// # Safety
// `ptr` must be a pointer returned by an `n4io_*` function that documents
// ownership transfer, or null. Passing any other pointer is undefined
// behaviour. Each such pointer must be freed exactly once.
void n4io_string_free(char *ptr);

#endif  /* NIRS4ALL_IO_H */
